### ISSUE TITLE
'cmap_black.sh' file is missing

### ISSUE THREAD

**Issue by KCallaghan** [CentreForHydrology/WDPM#1]
I am trying to run this using the WDPM.py file and it calls for a cmap_black.sh file, which is not included. The manual does not provide any description of this file for me to create it myself, so I suspect it should have been provided. 

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
You are quite right. It's distributed with the binary version of the program.
I'll add it to the repository.
Thanks very much

**Comment by KCallaghan** [comment]
Thanks. 
I downloaded the compiled version as well, and I could get the GUI launched by copying over the cmap_black.sh file from there (but please do still add it here!)
This is minor, but the version I compiled myself works better since the buttons don't appear properly on the compiled version. I couldn't find where the dropdown was supposed to be for 'method' until I was able to open the GUI in the version I had compiled myself:

![image](https://user-images.githubusercontent.com/41647227/83959631-d13e8780-a844-11ea-996d-bb5ef7d2d79f.png)

**Comment by KevinShook** [comment]
Which OS are you using? I seem to remember the same problem with the compiled version under Linux - but I never use the GUI. 
We'll update the compiled version.

**Comment by KCallaghan** [comment]
I'm using Linux Mint. 
I haven't figured out how to not use the GUI yet, but I'll get there!

**Comment by KevinShook** [comment]
That's great - I use Mint as well.
I'll check to see what's going on.
The parameters that you used look fine.
Thanks for checking all this

**Comment by KevinShook** [comment]
The file `cmap_black.sh` has been added, and the GUI Python code
has been changed to fix the problems caused by changes in Python

**Comment by KevinShook** [comment]
The GUI has been updated to Python 3 and now appears to work properly
