### ISSUE TITLE
Don't repeat yourself

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#12]
[These blocks](https://github.com/CentreForHydrology/WDPM/blob/master/src/WDPM.py#L1006-L1027) have near-duplicate functionality. Good coding practice is to abstract repetition into functions, please do so.

openjournals/joss-reviews#2276

**Comment by r-barnes** [comment]
[And again](https://github.com/CentreForHydrology/WDPM/blob/master/src/WDPM.py#L1029-L1055)

**Comment by r-barnes** [comment]
[And again](https://github.com/CentreForHydrology/WDPM/blob/master/src/WDPM.py#L32-L51)

**Comment by KevinShook** [comment]
The code has been cleaned up and we have removed the duplications

**Comment by r-barnes** [comment]
It is always helpful if you can include a commit hash so that it's easy to verify the change.
