### ISSUE TITLE
Abstract UI control

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#14]
[These lines](https://github.com/CentreForHydrology/WDPM/blob/master/src/WDPM.py#L294-L414) show a large amount of duplication. This could be reduced by looping over a list of components to enable/disable. It also suggests that perhaps the UI should be broken into separate controller classes that can be enabled/disabled separately. Handling everything in single mass code blocks is a recipe for low maintainability.

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
The duplication of lines has been fixed
