### ISSUE TITLE
Need a build system

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#16]
`WDPM/src/` contains C files and OpenCL files. These need a build system so they can be reproducibly compiled into a binary by the user. `CMake` is a strong, cross-platform choice. `Make` might be initially simpler to work with, but will be more challenging cross-platform.

An example of using CMake is [here](https://github.com/r-barnes/Barnes2019-DepressionHierarchy/blob/master/CMakeLists.txt). If you have difficulty working with cmake, please comment here and I can help.

openjournals/joss-reviews#2276

**Comment by r-barnes** [comment]
Actually, here's a decent `./CMakeLists.txt` file:
```
cmake_minimum_required (VERSION 3.9)

project (dephier LANGUAGES C)

find_package(OpenCL REQUIRED)

#Adds aggressive warnings to all compilation
if(MSVC)
  add_compile_options(/W4 /WX)
else()
  add_compile_options(-Wall -pedantic)
endif()

add_executable(wdpm-cl src/WDPMCL-Command-line.c)
target_link_libraries(wdpm-cl PRIVATE OpenCL)

add_executable(wdpm-gui src/WDPMCL-GUI.c)
target_link_libraries(wdpm-gui PRIVATE OpenCL)

#Include Python files in build output
ADD_CUSTOM_COMMAND(OUTPUT "${CMAKE_BINARY_DIR}/WDPM.py"
  COMMAND cmake -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/src/WDPM.py"
  "${CMAKE_BINARY_DIR}/WDPM.py"
  DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/WDPM.py"
  )
 list(APPEND pyfile_dest "${CMAKE_BINARY_DIR}/WDPM.py")
ADD_CUSTOM_TARGET(python ALL DEPENDS ${pyfile_dest})
```
See [this](https://github.com/r-barnes/Barnes2019-DepressionHierarchy) for an explanation of how to compile with `cmake`.

Everything, including the Python script, ends up in the `build` directory.

**Comment by KevinShook** [comment]
We are now using CMake

**Comment by r-barnes** [comment]
That seems to work, thanks.

**Comment by r-barnes** [comment]
The use of `set(CMAKE_C_FLAGS "-std=c11")` is antequated. Since, irrc, cmake 3.8 or earlier it is better to use
```
target_compile_features(TARGET_NAME PRIVATE cxx_std_11)
```
otherwise you pollute the flag-space.

https://cmake.org/cmake/help/latest/command/target_compile_features.html#command:target_compile_features

But I don't see why you're setting at C++ compilation flag for C code.

**Comment by r-barnes** [comment]
Also, please avoid `set(CMAKE_C_COMPILER "gcc")`. `cmake` will select an appropriate compiler or the user can specify with, e.g., `CC=gcc cmake -DCMAKE_BUILD_TYPE=Release ..`

**Comment by r-barnes** [comment]
`project(WDPMCL)` should appear once at the top of the CMakeLists.txt file.

**Comment by r-barnes** [comment]
Why does
```
	find_package(PythonInterp 3 REQUIRED)
	find_package(PythonLibs 3 REQUIRED)
```
Appear in the `CMakeLists.txt` file? It doesn't appear as though you're using Python in the compilation process.

**Comment by r-barnes** [comment]
I've put up a pull request #56 to fix some of these issues.

**Comment by KevinShook** [comment]
Thanks very much

**Comment by r-barnes** [comment]
Worked fine this time. Closing.
