### ISSUE TITLE
Indicate dependencies

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#19]
I haven't seen any file indicating code dependencies.

For Python, a [`requirements.txt`](https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers) file would be helpful.

For other dependencies, such as `gdaldem`, which appears in `WDPM/src/cmap_black.sh`, the README file or a conda requirements file should indicate the dependency.

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
A requirements.txt file has been added, and the external software required is now referenced in README.md as well as in the program manual.

**Comment by r-barnes** [comment]
I think the `requirements.txt` file should be in more standard location of the root directory, rather than `src/`.

**Comment by KevinShook** [comment]
Done. 
Commit 9d37dfd

**Comment by r-barnes** [comment]
Looks good, thanks!
