### ISSUE TITLE
Missing CL subdirectory

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#25]
Overlaps with #16, #20, and/or #23.

Following the compilation instructions given in the manual [here](https://research-groups.usask.ca/hydrology/modelling/wdpm.php), I find that the program is missing a `CL` subdirectory.

```
$ gcc WDPMCL-Command-line.c -lOpenCL -o WDPMCL
WDPMCL-Command-line.c:25:10: fatal error: CL/cl.h: No such file or directory
   25 | #include <CL/cl.h>
      |          ^~~~~~~~~
compilation terminated.
```

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
This has now been fixed. The directory will be correctly accessed when the OpenCl drivers are installed.

**Comment by awickert** [comment]
I can confirm that WDPM now successfully compiles (with the help of cmake) on my computer following the instructions in the manual.
