### ISSUE TITLE
Rainfall/snowmelt relative importance

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#26]
In the paper, you claim:

"Addition of water could be caused by rainfall, but in the Prairies it is more commonly due to snowmelt runoff."

Can you cite a reference showing that this is true? Considering that the formerly-glaciated prairies cover a large north--south extent, I am not sure that this is the case everywhere, or even in most cases.

https://github.com/openjournals/joss-reviews/issues/2276

**Comment by KevinShook** [comment]
This is certainly the case in the Canadian Prairies where the majority of annual runoff is caused by snowmelt and the depressions actively trap blowing snow. This has been clarified and a supporting reference has been added.

**Comment by awickert** [comment]
Agreed for Canada! (We also have Prairies down here ;) )
