### ISSUE TITLE
Evaporation > infiltration?

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#27]
You state:

"Subtraction of water may be due to infiltration to the soils, but in the Prairies it is more commonly caused by evaporation."

Could you cite a source demonstrating that this is the case?

https://github.com/openjournals/joss-reviews/issues/2276

**Comment by KevinShook** [comment]
In the Canadian Prairies, depressions are commonly underlain by deep deposits of glacial till, with very low permeabilities.
A supporting reference has been added.

**Comment by awickert** [comment]
Excellent.
