### ISSUE TITLE
Capitalization of Prairie

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#28]
Could you explain what makes Prairie a proper noun? Is there a specific prairie region that you have in mind, and/or is this simply convention in Canadian English?

https://github.com/openjournals/joss-reviews/issues/2276

**Comment by KevinShook** [comment]
We typically capitalise prairie when we are referring to the Canadian Prairies (a proper noun) rather than prairies in general. This has been tidied to make sure that we are using the appropriate capitalization.

**Comment by awickert** [comment]
Okay!
