### ISSUE TITLE
Paper: clarification

### ISSUE THREAD

**Issue by awickert** [CentreForHydrology/WDPM#29]
* "Removing the water and smoothing to a tolerance of 1 mm required 1,000 iterations - the minimum possible."
  * *The minimum possible what?*

* " by several government agencies and by private consultants."
  * *Could you provide examples and/or references?*

**Comment by kbarnhart** [comment]
openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
The minimum possible refers to the number of iterations.The minimum possible is 1000 as the iterations are only checked every thousand.
Unfortunately, private consultants and government agencies, don't often publish in refereed literature, but we do have records of them downloading the software. We have cited one government agency in armstrongUSINGWETLANDPONDING2013a, perhaps the citation should be after the statement. We can also refer to the downloads of the software without releasing the names of the users.

**Comment by awickert** [comment]
Maybe you could include the number of software downloads as of a certain date, and then use in combination with reports?

**Comment by KevinShook** [comment]
That's a good idea. I'll also contact some of the users to see if they have published anything in grey literature

**Comment by KevinShook** [comment]
Have added the number of downloads and have added some citations for consultants.

**Comment by awickert** [comment]
The updates look good to me.
