### ISSUE TITLE
Can't run program via GUI

### ISSUE THREAD

**Issue by KCallaghan** [CentreForHydrology/WDPM#3]
I'm getting some inconsistent behaviour and I'm not sure if it is user error or if the program just isn't working. 

On the version I have compiled myself: 
Once I press start, the following comes up: 

```
Please wait ........................
                                          
Program arguments in order of specification
Add module specified
Path and Name of Report file
DEM file name (string)
Water file name (string)
Output file name (string)
Scratch file name (string) - Optional, use --NULL-- to omit
Depth of water to add (mm) (real)
Water runoff fraction (real)
Elevation tolerance (mm) (real)
Specify 0 for serial CPU and 1 for opencl 
Specify 0 for OpenCL CPU and 1 for opencl GPU 
```

and then nothing further happens. If I click 'end', it says that the simulation is not running. No result file is created. My settings are shown in the image. 
![image](https://user-images.githubusercontent.com/41647227/83959989-35634a80-a849-11ea-908b-254b46db1d45.png)

Strangely, one time when I ran this, it _did_ create a reasonable-looking output file. I am not certain what my exact settings were for that one time since I had not yet realised this was an issue, but I think they were the same as in the screenshot. I have not been able to make this work a second time.

In the binary version I downloaded, the statements printed out are different, and this one seems to specify an error: 
`Couldn't identify a platform: No such file or directory`
I am not sure which file it can't find. 

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
It looks like the GUI issues were caused by a change in Python.
The Python code has been changed and appears to work
correctly.
Specifically, the instances of `wx.OPEN` had to be changed to `wx.FD_OPEN`.
We hadn't noticed this because we never use the GUI!

**Comment by KCallaghan** [comment]
This issue is ongoing for me, no change.

**Comment by KevinShook** [comment]
The GUI has been fixed. Apart from problems caused by the switch to Pyhton 2 to 3, we have also solved an issue which was causing the program to run more slowly from the GUI.

**Comment by KCallaghan** [comment]
I am no longer experiencing this issue, thanks.
