### ISSUE TITLE
Clarification on race conditions

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#59]
I see this
> Because the matrix locations of each thread are separated by 3 rows and columns, the points are independent, and race conditions are avoided.

But it's unclear to me how this makes it safe since hydrological interactions tend to propagate. A citation or more complete explanation here would be useful.

**Comment by KevinShook** [comment]
Water is distributed to the 8 cells surrounding a given cell. If two cells are 3 elements apart in any direction, then by definition any water distribution involving these cells is independent as the cells do not communicate directly. 
Therefore, it is safe to allow all of the operations to proceed on these separated cells using any number of threads as
no race conditions can exist where one thread changes the water depth used by another. Of course water may flow between two cells 3 or more elements apart, but the movement occurs through intermediary cells as each is evaluated.
I will update the explanation.

**Comment by KevinShook** [comment]
Added to paper,
commit  ece23e5

**Comment by r-barnes** [comment]
Thanks.
