### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#67]
I'm not finding a test suite.

[This site](https://realpython.com/pytest-python-testing/) explains how to build one.

In our recent FillSpillMerge work we used randomized testing to generate hundreds of thousands of artificial landscapes and then tested
1. To see if adding a very large amount of water gives a result exactly equal to depression filling,
2. That incrementally adding portions of water gives the same result as adding the same amount of water all at once
3. And more, see [link](https://github.com/r-barnes/Barnes2020-FillSpillMerge/blob/master/unittests/fsm_tests.cpp) for details. 

Performing extensive tests identified bugs in our software and we were able to fix them before they impacted downstream science. Given the complexity of WDPM having a good set of unittests seems appropriate.

**Comment by KevinShook** [comment]
Thanks for the suggestion. We are looking into setting up automated unit tests.
The OpenCL kernel file `runoff.cl`, which does the parallelised water distribution calculations, is very small (183 lines)
and has not changed since 2014 (other than the very recent change from tabs to spaces),
so we hadn't been using automated tests. 

Our focus has always been using on WDPM for real-world landscapes. Because WDPM outputs standard .asc files, we
have used GIS scripts in R to validate the results of WDPM against prior versions, for differing landscapes.
As we are interested in the connected/contributing fractions of prairie landscapes, and how they change with the state of water, it's been important to evaluate any changes in the program outputs with respect to many sequences of additions and removals of water.

**Comment by kbarnhart** [comment]
@KevinShook sorry I didn't notice your comment here until now. 

One point I'd like to make is that JOSS is less concerned with how testing is implemented over whether appropriate tests have been developed and there are instructions on how to run and evaluate them. This is to say, if a user is asked to run a script from the command line which runs a series of additions and removals (perhaps on your basin5.asc file) and then compares the results to a set of benchmark files, that is totally fine. While an automatic test suite is certainly the "best in class" version of testing, it is not necessarily required. The more important characteristic of testing is that an appropriately designed set of tests exist. 

I hope this point is helpful. Please let me know if I might be able to provide additional clarifications or guidance.

**Comment by KevinShook** [comment]
As the primary output from WDPM is just a file of water depths, it requires quite a bit of post-processing. For example, these are the types of figures that I typically use. The first shows frequency distributions of water areas for 3 sequences (addition, removal and subsequent addition of water). It is necessary to find all of the water areas in each model output dataset, which requires GIS or an R script.

![Figure10](https://user-images.githubusercontent.com/11050573/123988154-030d1980-d985-11eb-84a1-55b0ba00fd0e.png)

The second shows the change in the connected fractions of a single basin, using DEMs with varying resolutions. In this case, each point is computed by adding (or removing) water, draining, then adding 1 mm, followed by draining. The change in the water storage, when subtracted from the volume of water added, and divided by the same volume is used to represent the connected/contributing fraction. We also use an R script to do this.
![WDPMresolutionScalingROF](https://user-images.githubusercontent.com/11050573/123987654-9bef6500-d984-11eb-940c-88e0c8aa2ab9.png)

However, I very much agree with your point, that it is important that the user be able to validate that the model is running correctly. I think that we can do this by using the WDPM log files. Normally these are just used to ensure that the 
program is running correctly. However, the log file also contains several statistics w.r.t. the state of the water
storage at the end of the run, such as the total water volume, mean/max depth and areal water fraction. 

I will set up scripts to add, subtract and drain water, and will explain their use, and the results that should be
expected by the user. Would that be OK?

**Comment by kbarnhart** [comment]
@KevinShook I think there are a lot of different ways to go about constructing tests for this type of algorithm. One way could be the approach you describe. I'm not quite sure that this approach is fully necessary, though. 

An approach I've found useful for constructing test is to identify a synthetic case that (a) is complex enough to interact with the full algorithm and (b) is small enough that I can hand calculate the expected outcome from the algorithm. For example, I might use something like the below DEM. Constructed so it has two depressions, one larger and more complex, and one smaller. 

```
10.0    10.0    10.0    10.0   10.0    10.0
10.0     9.0     8.0     9.0   10.0    10.0
10.0     7.0     5.0    10.0   10.0    10.0
10.0    10.0    10.0    10.0    4.0    10.0
10.0    10.0    10.0    10.0   10.0    10.0
```

I might then perform a series of add/subtract/drain and at each step assert that the results are correct. Such an assertion could could manifest in a few ways. For example, it could assert that mass is conserved and that the spatial distribution of water depths is as expected, both within the expected tolerance. 

Such an approach tests the core algorithms, but on such a small scale that it is possible to know what the results should be. 

There are a few ways any sort of testing approach might be implemented. One option would be to write a script that sets up these tests (could include writing a temporary .asc file with the synthetic grid), runs them, prints a useful message ("All tests pass", statement about where tests failed) based on the comparison between model results and expected results, and then cleans up any temporary files. Another option would be to use packages like pytest which help with discovery and evaluation of tests. 

Hope this is helpful guidance. Happy to continue discussing as needed.

**Comment by KevinShook** [comment]
Thanks. I had been thinking of something like this, but was stumped by the need to build
a system which would not require the development of further software (which would itself
require testing), and would be platform-agnostic. Something like this can easily be done in Linux
(which I use exclusively), probably using awk, but is much more difficult for Windows, which is used by
the majority of people running WDPM. However, with the advent of WSL we should be able to build a single
script.

**Comment by kbarnhart** [comment]
@KevinShook this all sounds good to me. If anything comes up where I can provide guidance and/or input, let me know.

**Comment by KevinShook** [comment]
I have added scripts to validate the WDPM output. They are in the `/validation` directory.
The scripts are described in the file `WDPM_validation.md`.
There's a bash script which runs WDPM using the add, drain and subtract modules. It also
calls 3 awk scripts which test the outputs. All 3 scripts check the water stored in a small depression.
The `add_test.awk` scripts also independently checks the conservation of mass. The `drain_test.awk` script checks that
the remaining volume of water is correct, and also checks that the depth at the outlet is zero.
The `subtract_test.awk` script also checks the remaining volume of water.

**Comment by kbarnhart** [comment]
@KevinShook I'll be able to look more carefully at this in the next day or two.

**Comment by kbarnhart** [comment]
@KevinShook I've taken a look at this, tried it out, and think it is good. I'm going to make a note on the main review thread that I think it makes sense for @r-barnes to revisit his review.

**Comment by KevinShook** [comment]
Thanks very much

**Comment by kbarnhart** [comment]
@KevinShook I don't have permissions to close this issue, but I think you can close it.
