### ISSUE TITLE
Contributors guide

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#68]
I can't find a contributors guide.

See https://github.com/holukas/dyco/blob/main/CONTRIBUTING.md for an example

**Comment by r-barnes** [comment]
This is for the "Community Guidelines" section of the review checklist

**Comment by KevinShook** [comment]
Thanks for pointing this out.
We are such a small project, that I never considered it.
We have added CONTRUIBUTING.md as well as a code of conduct in commit 
https://github.com/CentreForHydrology/WDPM/commit/09d5787a938a751dff4b68837a0753d582090c0a

**Comment by kbarnhart** [comment]
@KevinShook I don't have permissions to close this issue, but I think you can close it.
