### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#69]
"Computation Settings" don't appear to be documented in the manual. Other settings from the GUI may also be undocumented.

Although the manual should document everything since you're otherwise relying heavily on it for this purpose, using tooltips in the GUI would be a much more accessible way of communicating the information, eg, https://codeloop.org/how-to-create-tooltip-in-wxpython/

**Comment by KevinShook** [comment]
"Computation Settings" is a title, not a program setting.
All of the individual settings were documented in the manual, however the title
is now referred to explicitly in the manual, in commit
https://github.com/CentreForHydrology/WDPM/commit/b27e3446d9f78b83c58e8a0d4f0bebd608060eb5

**Comment by kbarnhart** [comment]
@KevinShook I don't have permissions to close this issue, but I think you can close it.
