### ISSUE TITLE
Executable files unavailabe

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#7]
The link in the README (http://www.usask.ca/hydrology/WDPM.php) redirects to (https://research-groups.usask.ca/hydrology/). There are no executables available here.

Executables should rarely, if ever, be distributed with a Git repo. The repo should contain sufficient material to generate the executables.

openjournals/joss-reviews#2276

**Comment by KevinShook** [comment]
Unfortunately, the website was changed after the JOSS submission.
I can update the link in the README, unless you think that there should not be a link at all.

**Comment by r-barnes** [comment]
If the link is to binaries generated by the C and OpenCL programs in the repo, I think it would be better to focus your attention on the build system for the binaries. That eliminates the worry about maintaining the structure of the external website and ultimately make the work more reproducible. So, yes, I'd drop the link.

Let me know if I can be of assistance.

**Comment by KevinShook** [comment]
The documentation has been updated to reflect the new location of other supporting files.
We have removed all binaries from the other website, except for a Windows binary, as we don't expect that
most Windows users will be able to compile the program.
