### ISSUE TITLE
C code formatting

### ISSUE THREAD

**Issue by r-barnes** [CentreForHydrology/WDPM#70]
In the C code I see inconsistent formatting like so:
```
    final_vol=final_vol*cellarea;
    meanwater = watertotal/((float)watercount);
    basincount=0;
      for(i=0; i<numrows; i++){
    for(j=0; j<numcols; j++){
	    if(dem[i][j]>missingvalue){
            basincount++;
	    }
	}
    }
```
This is because the code intermixes tabs and spaces. It's likely that my tab display width is different from yours.

Please reformat the code to consistently use only spaces for whitespace (this is a common requirement of coding [style guides](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs)).

**Comment by KevinShook** [comment]
Fixed `runoff.cl` in commit https://github.com/CentreForHydrology/WDPM/commit/2583bd84c721add483037b86bee3d89ece0701d9 . The file `WDPMCL.c` was fixed in a prior commit.

**Comment by kbarnhart** [comment]
@KevinShook I don't have permissions to close this issue, but I think you can close it.
